### ISSUE TITLE
Questions regarding auto-updating setup for nixpkgs

### ISSUE THREAD

**Issue by Frontear** [nix-community/nixpkgs-update#434]
Hi! I'm a maintainer for a package upstream called `stevenblack-blocklist`, and about 2 releases ago I added a `passthru.updateScript` in hopes the bot account could push updates for me automatically. Since then, 2 releases have been made for the package's upstream, and neither was caught and updated. I wanted a second opinion on whether I had setup the updating script done wrong. I had tested it via the maintainers script by bumping it back a few revisions older and it updated without a hitch in testing, so I was curious what might be happening now.

The package can be found here: https://github.com/NixOS/nixpkgs/blob/a6c83f4952ad4e43176cb3bda4f2cf7e08ffd321/pkgs/by-name/st/stevenblack-blocklist/package.nix#L57.

P.S. it seems the front-facing website for the logs is down, as I haven't been able to come check it for logs regarding my package: https://nixpkgs-update-logs.nix-community.org/

**Comment by rhendric** [comment]
Huh, server seems to be up at the moment.

I see from https://nixpkgs-update-logs.nix-community.org/stevenblack-blocklist/2024-07-06.log that the script was triggered last Saturday but there were no updates available then. It can take several days for the service to get back around to a package that was recently checked; it prioritizes packages by how long it has been since they've been checked for an update. Running your update script locally, it seems to be working fine.

**Comment by Frontear** [comment]
Gotcha, guess I'll be a little more patient. Thanks for the info!
